# Loops

- while
- for

## While Loops
while \*condition\*
    
    *loop body*
    
end

In [3]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [5]:
friends = ["jane", "greta", "lacy"]
i = 1
while i <= length(friends)
    friend = friends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi jane, it's great to see you!
Hi greta, it's great to see you!
Hi lacy, it's great to see you!


## For Loops
for \*var\* in \*loop iterable\*

    *loop body*
    
end

In [6]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [7]:
for friend in friends
    println("Hi $friend, it's great to see you!")
end

Hi jane, it's great to see you!
Hi greta, it's great to see you!
Hi lacy, it's great to see you!


You can replace `in` with either `=` or `is an element of sign`

In [8]:
for n = 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


Let's make matrices!!!!
(everybody loves a good matrix)
m and n are the rows and columns of the matrix, using `zeros` (no 'e') create the matrix with '0.0' at every point.

In [12]:
m, n = 5, 5
A = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [17]:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

You can combine the for loops to make it prettier

In [19]:
B = zeros(m, n)
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

Or... you can use an *array comprehension*, where you don't need to initialize the matrix.

In [20]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

You can even embed an array comprehension inside of a `for` loop.

In [21]:
for n in 1:10
    A = [i+j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

It's so PRETTY!!!